### ISSUE TITLE
Conflicts found in inverse config after last update.

### ISSUE THREAD

**Issue by Wansmer** [nguyenvukhang/nvim-toggler#12]
After commit [2ce3146](https://github.com/nguyenvukhang/nvim-toggler/commit/2ce31467720cc946913ac5145570ddab69a9d454) the plugin notify `[nvim-toggler] conflicts found in inverse config.` six times.
<img width="475" alt="notify" src="https://user-images.githubusercontent.com/46977173/205441053-fed1cde4-9330-4a2c-b144-6a5be0b67529.png">

**Comment by nguyenvukhang** [comment]
This suggests that you might have conflicts in the configured inverses.

edit: possibly you might want to disable the default inverses:
```lua
require('nvim-toggler').setup({
  remove_default_inverses = true,
})
```

But either way six times is a bit much. I'll change the plugin to only notify once.
