### ISSUE TITLE
[Suggestion] new project name!

### ISSUE THREAD

**Issue by Icy-Thought** [nguyenvukhang/nvim-toggler#13]
The project name should be self-explanatory, in my opinion. Because of this I propose to you a project name that I had come up with while watching the demonstration video found in the README of this project:

1. `nvim-antonym`
2. `antonym.nvim`

or something of that sort.

**Comment by nguyenvukhang** [comment]
Interesting notion. This plugin is pretty general and doesn’t restrict users to using antonyms only, though that might probably be the most common use case.
