### ISSUE TITLE
Remapping does not work

### ISSUE THREAD

**Issue by jgollenz** [nguyenvukhang/nvim-toggler#2]
There is currently no way to truly remap the default keybinding of `<Leader>i`. The option mentioned in the README will create an additional keybinding, but the default one will still persist.

**Comment by nguyenvukhang** [comment]
I guess that's intended for now.

Usually plugins come with a set of default keymaps and it's on the user to define their own custom remaps after sourcing the plugins, to ensure that their own remaps are not overriden.

**Comment by jgollenz** [comment]
I respectfully disagree. Most nvim plugins I use either offer a way to truly override the mappings via a setup function or use a command like `:ZenMode` for which users can specify their desired mapping while no default mapping is set in the first place. Either way, I don't have to worry about dangling default mappings. I would not consider it low friction when a plugin leaves some default mappings around for me to manually disable, if I don't want them. 
Furthermore, in my opinion the wording 'remap' is kinda misleading here. If the README mentions how to add *another* mapping, it should also mention how the default mapping can be disabled.

**Comment by nguyenvukhang** [comment]
fixed in 9346d5b
