### ISSUE TITLE
Inverse matching inconsistent

### ISSUE THREAD

**Issue by jgollenz** [nguyenvukhang/nvim-toggler#3]
![cword](https://user-images.githubusercontent.com/12050098/185921974-91828212-d2eb-4df3-bdb4-bd588e0ef9f6.gif)

Currently the plugin checks for the `<cword>` under the cursor. This will not work for e.g. `==` inside this line `if (foo == bar) {`. The detected cword when on the equality operator is `bar`. I have not yet completely understood the behavior. From `:h word`:

```
A word consists of a sequence of letters, digits and underscores, or a
sequence of other non-blank characters, separated with white space (spaces,
tabs, <EOL>).  This can be changed with the 'iskeyword' option.  An empty line
is also considered to be a word.
```

So I guess when there is an alphanum+underscore word after `==` it will detect that, otherwise it falls back to a sequence of non-blank characters and finds `==`. 

There is also `<cWORD>` which will detect `==`, but also fails to detect `true` when e.g. wrapped like this: `"true"`. That's because cWORD only takes non-blank character sequences (see `:h WORD`).

One idea would be to first match against cword and then against cWORD, but this will fail in a situation like the following: `if (my_var == true)`. Here cword will match with `true` and replace the equality operator with the inverse, `false` (as can be seen in the video). 

Another one would be to match each key in the lookup-table against cWORD and only toggle the matched part of the cWORD. But again, what about a situation where one has `<` and `<<` in the lookup table? Would it toggle the first occurrence? All occurrences? Is it correct by accident?

Finally, it is possible to modify what counts as a word via the `iskeyword` option. However, this may have unwanted side-effects and should therefore probably only be done by the users themselves. 

I have no solution for this yet, will investigate further.

PS: @nguyenvukhang I will continue posting issues that others might encounter here if you don't mind, for documentation purposes. Of course, only issues that happen with the base repo, not just in my fork :+1:

**Comment by nguyenvukhang** [comment]
Fixed with 9346d5b.

`nvim-toggler` now injects a custom `iskeyword` config just before toggling and sets it back after toggling.
