### ISSUE TITLE
support the third string

### ISSUE THREAD

**Issue by oeyoews** [nguyenvukhang/nvim-toggler#5]
Is it possible to support three string to switch each other， like `vim -> emacs -> vscode -> vim`

**Comment by nguyenvukhang** [comment]
Yeah that's doable, though I'm curious, what would be your real-life use case of this?

**Comment by oeyoews** [comment]
Just a whim, I noticed that left address and right value cant repeat(recursive pass）in inverses table

![image](https://user-images.githubusercontent.com/72405338/186175621-3ece3dd8-77db-47dc-8653-b4ee15b60e3e.png)

**Comment by nguyenvukhang** [comment]
Yeah the current implementation adds a reverse-lookup on the `inverses` table.
It seems that the config in that screenshot causes an error upon entering neovim.

I guess that's a good thing because it catches invalid configurations, though I think I can probably handle it more elegantly.
